server:
  port: 9191

spring:
  application:
    name: API-GATEWAYE

  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          #uri: http://localhost:9002/
          uri: lb://EMPLOYEE-SERVICE/
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri:
                  forward:/employeeServiceFallBack

        - id: DEPARTMENT-SERVICE
          #uri: http://localhost:9001/, http://localhost:9003/
          uri: lb://DEPARTMENT-SERVICE/
          predicates:
            - Path=/api/v1/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/departmentServiceFallBack
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true




resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

      DEPARTMENT-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

